export const SEQUELIZE = 'SEQUELIZE';
export const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';
export const CARD_REPOSITORY = 'CARD_REPOSITORY';
export const NEWS_REPOSITORY = 'NEWS_REPOSITORY';
export const NEWS_MEDIA_REPOSITORY = 'NEWS_MEDIA_REPOSITORY';
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const ORDER_STATUS_REPOSITORY = 'ORDER_STATUS_REPOSITORY';
export const PROFILE_REPOSITORY = 'PROFILE_REPOSITORY';
export const ORDER_PRODUCT_STATUS_REPOSITORY =
  'ORDER_PRODUCT_STATUS_REPOSITORY';
export const ORDER_PRODUCT_REPOSITORY = 'ORDER_PRODUCT_REPOSITORY';
export const TYPE_MEDIA_REPOSITORY = 'TYPE_MEDIA_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_AILMENTS_REPOSITORY = 'PRODUCT_AILMENTS_REPOSITORY';
export const AILMENT_REPOSITORY = 'AILMENT_REPOSITORY';
export const AILMENTS_IMAGES_REPOSITORY = 'AILMENTS_IMAGES_REPOSITORY';
export const SALE_REPOSITORY = 'SALE_REPOSITORY';
export const PRODUCT_IMAGES_REPOSITORY = 'PRODUCT_IMAGES_REPOSITORY';
export const PRODUCT_PARTS_REPOSITORY = 'PRODUCT_PARTS_REPOSITORY';
export const SUPPLY_REPOSITORY = 'SUPPLY_REPOSITORY';
export const SHOPPING_CART_REPOSITORY = 'SHOPPING_CART_REPOSITORY';
export const DELIVERY_TIME_REPOSITORY = 'DELIVERY_TIME_REPOSITORY';
export const ADDRESS_DELIVERIES_TIME_REPOSITORY =
  'ADDRESS_DELIVERIES_TIME_REPOSITORY';
export const SUBSCRIPTION_STATUS_REPOSITORY = 'SUBSCRIPTION_STATUS_REPOSITORY';
export const SUBSCRIPTION_PRODUCT_STATUS_REPOSITORY =
  'SUBSCRIPTION_PRODUCT_STATUS_REPOSITORY';
export const SUBSCRIPTION_REPOSITORY = 'SUBSCRIPTION_REPOSITORY';
export const SUBSCRIPTION_PRODUCT_REPOSITORY =
  'SUBSCRIPTION_PRODUCT_REPOSITORY';
export const ORDER_SUBSCRIPTION_REPOSITORY = 'ORDER_SUBSCRIPTION_REPOSITORY';
export const WMS_CUSTOMER_REQUIREMENT_ENTITY_PROVIDERS =
  'WMS_CUSTOMER_REQUIREMENT_ENTITY_PROVIDERS';
export const WMS_CUSTOMER_REQUIREMENT_DETAIL_ENTITY_PROVIDERS =
  'WMS_CUSTOMER_REQUIREMENT_DETAIL_ENTITY_PROVIDERS';
export const POSTAL_CODES_REPOSITORY = 'POSTAL_CODES_REPOSITORY';
export const SUPPLY_REQUEST_REPOSITORY = 'SUPPLY_REQUEST_REPOSITORY';
export const USER_AILMENTS_REPOSITORY = 'USER_AILMENTS_REPOSITORY';
export const DOSING_SETUP_REPOSITORY = 'DOSING_SETUP_REPOSITORY';
export const DOSES_TAKEN_REPOSITORY = 'DOSES_TAKEN_REPOSITORY';
export const USER_AILMENTS_PRODUCT_REPOSITORY =
  'USER_AILMENTS_PRODUCT_REPOSITORY';
